const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const test = require('node:test')
const { createLocalProjectStore } = require('../src/project-store.cjs')
const { AGNES_MODELS, AGNES_PROVIDER_ID } = require('../src/agnes-model-catalog.cjs')

test('covers use verified canvas image results without switching the active project', async (t) => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'vibepaper-cover-'))
  const store = createLocalProjectStore()
  t.after(async () => { await store.close(); await fs.rm(directory, { recursive: true, force: true }) })
  const first = await store.createProject(directory, 'Images')
  const scope = { projectId: first.project.projectId, canvasId: first.project.canvasId }
  assert.equal(await store.resolveProjectCover(first.directory, scope), null)
  const created = await store.createNode({ ...scope, type: 'image', params: {}, expectedVersion: 0, idempotencyKey: 'image' })
  const task = await store.createTask({ ...scope, canvasVersion: created.version, nodeId: created.node.id,
    modality: 'image', providerType: 'cloud', providerId: AGNES_PROVIDER_ID, modelId: AGNES_MODELS.image,
    idempotencyKey: 'image-task', parameters: { prompt: '小猫' } })
  const claimed = await store.claimNextTask(scope.projectId)
  const bytes = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZkAAAAASUVORK5CYII=', 'base64')
  const filePath = path.join(claimed.outputDirectory, 'result.png')
  await fs.writeFile(filePath, bytes)
  await store.recordTaskSucceeded(scope.projectId, task.taskId, `generated/${task.taskId}/result.png`)
  const cover = await store.resolveProjectCover(first.directory, scope)
  assert.equal(cover.filePath, filePath)
  assert.equal(cover.mimeType, 'image/png')
  const second = await store.createProject(directory, 'Other')
  assert.deepEqual(await store.resolveProjectCover(first.directory, scope), cover)
  assert.equal(store.getActiveProject().projectId, second.project.projectId)
  await assert.rejects(store.resolveProjectCover(first.directory, { ...scope, projectId: second.project.projectId }), /身份/)
  await fs.writeFile(filePath, Buffer.concat([bytes, Buffer.from('changed')]))
  assert.equal(await store.resolveProjectCover(first.directory, scope), null)
  assert.equal(store.getActiveProject().projectId, second.project.projectId)
})
