const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('vibepaperDesktop', {
  getActiveProject: () => ipcRenderer.invoke('desktop:project:get-active'),
  createProject: (name) => ipcRenderer.invoke('desktop:project:create', name),
  openProject: () => ipcRenderer.invoke('desktop:project:open'),
  backupProject: (projectId) => ipcRenderer.invoke('desktop:project:backup', projectId),
  restoreBackup: () => ipcRenderer.invoke('desktop:project:restore-backup'),
  importImage: (projectId) => ipcRenderer.invoke('desktop:asset:import-image', projectId),
  listAssets: (projectId) => ipcRenderer.invoke('desktop:asset:list', projectId),
  loadCanvas: (projectId, canvasId) => ipcRenderer.invoke('desktop:canvas:load', projectId, canvasId),
  saveCanvas: (input) => ipcRenderer.invoke('desktop:canvas:save', input),
  listTasks: (projectId, limit) => ipcRenderer.invoke('desktop:task:list', projectId, limit),
  cancelTask: (projectId, taskId) => ipcRenderer.invoke('desktop:task:cancel', projectId, taskId),
  createGenerationTask: (input) => ipcRenderer.invoke('desktop:task:create-generation', input),
  readTaskOutput: (projectId, taskId) => ipcRenderer.invoke('desktop:task:read-output', projectId, taskId),
  getAgnesModels: () => ipcRenderer.invoke('desktop:model:get-agnes'),
  saveAgnesApiKey: (apiKey) => ipcRenderer.invoke('desktop:model:save-agnes-key', apiKey),
  clearAgnesApiKey: () => ipcRenderer.invoke('desktop:model:clear-agnes-key'),
  getLocalTextModel: () => ipcRenderer.invoke('desktop:model:get-local-text'),
  discoverLocalModels: (endpoint) => ipcRenderer.invoke('desktop:model:discover-local', endpoint),
  saveLocalTextModel: (config) => ipcRenderer.invoke('desktop:model:save-local-text', config),
  clearLocalTextModel: () => ipcRenderer.invoke('desktop:model:clear-local-text'),
  listAgentSessions: (projectId) => ipcRenderer.invoke('desktop:agent:list-sessions', projectId),
  createAgentSession: (projectId, title) => ipcRenderer.invoke('desktop:agent:create-session', projectId, title),
  getAgentMessages: (projectId, sessionId) => ipcRenderer.invoke('desktop:agent:get-messages', projectId, sessionId),
  sendAgentMessage: (projectId, sessionId, content) => ipcRenderer.invoke('desktop:agent:send-message', projectId, sessionId, content),
})
