// Native dialog labels only. User filenames, paths and content are preserved.
module.exports = {
  "本地核心已停止": "Local core stopped",
  "本地项目服务意外退出。请重新启动 Pi-Paper 后继续。": "The local project service exited unexpectedly. Restart Pi-Paper to continue.",
  "选择编组下载位置": "Choose a folder for group downloads",
  "选择新项目的保存位置": "Choose a folder for the new project",
  "打开 Pi-Paper 本地项目": "Open a Pi-Paper local project",
  "选择项目备份保存位置": "Choose a location for the project backup",
  "项目备份完成": "Project backup complete",
  "本地项目备份已创建，包含支持的 Agent 会话与记忆文件。": "Local project backup created, including supported Agent sessions and memory files.",
  "选择要恢复的 Pi-Paper 项目备份": "Select a Pi-Paper project backup to restore",
  "选择恢复副本的保存位置": "Choose a folder for the restored copy",
  "备份恢复完成": "Backup restored",
  "已创建并打开恢复副本。": "The restored copy has been created and opened.",
  "导入本地图片素材": "Import local images",
  "导入本地素材": "Import local assets",
  "批量导入本地素材": "Import local assets in bulk",
  "替换本地图片素材": "Replace local image",
  "替换本地音频素材": "Replace local audio",
  "替换本地素材": "Replace local asset",
  "选择导入画布的新项目保存位置": "Choose a folder for the imported canvas project",
  "导入本地 Markdown Skill": "Import a local Markdown Skill",
  "Pi-Paper 启动失败": "Pi-Paper could not start",
  "下载节点结果": "Download node output",
  "节点结果": "Node output",
  "图片": "Images",
  "音频": "Audio",
  "视频": "Video",
  "文本": "Text",
  "所有文件": "All files"
}
