/** Verified API identities and capabilities of adapters implemented in this repository. */
export const OFFICIAL_MEDIA_MODELS: Record<string, Record<string, unknown>> = {
	"Wan 2.7": {
		apiModelId: "wan2.7-t2v",
		providerId: "alibaba-video",
		brandId: "alibaba",
		operation: "task",
		inputModes: ["text"],
		defaults: { resolution: "1080P", duration: 5, ratio: "16:9", prompt_extend: true, watermark: false },
		constraints: {
			acceptedResolutions: ["720P", "1080P"],
			acceptedAspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4"],
			minimumDuration: 2,
			maximumDuration: 15,
			maximumReferences: 0,
			supportsGenerateAudio: false,
			accountAccessNotice: "当前画布绑定文生视频接口；图生及参考图接口不能通过此绑定调用。",
		},
	},
	"Happyhorse 1.1": {
		apiModelId: "happyhorse-1.1-t2v",
		providerId: "alibaba-video",
		brandId: "alibaba",
		operation: "task",
		inputModes: ["text"],
		defaults: { resolution: "1080P", duration: 5, ratio: "16:9", watermark: true },
		constraints: {
			acceptedResolutions: ["480P", "720P", "1080P"],
			acceptedAspectRatios: ["16:9", "9:16", "1:1", "4:3", "3:4", "4:5", "5:4", "9:21", "21:9"],
			minimumDuration: 3,
			maximumDuration: 15,
			maximumReferences: 0,
			supportsGenerateAudio: false,
			accountAccessNotice: "使用阿里云百炼视频凭据；当前画布绑定文生视频接口，官方默认带水印。",
		},
	},
	"MiniMax Hailuo 2.3 Fast": {
		apiModelId: "MiniMax-Hailuo-2.3-Fast",
		operation: "task",
		apiBaseUrl: "https://api.minimax.io/v1",
		inputModes: ["image"],
		defaults: {
			resolution: "768P",
			duration: 6,
			ratio: "adaptive",
			prompt_optimizer: true,
			fast_pretreatment: false,
		},
		constraints: {
			acceptedResolutions: ["768P", "1080P"],
			acceptedAspectRatios: ["adaptive"],
			minimumDuration: 6,
			maximumDuration: 10,
			acceptedDurations: [6, 10],
			durationByResolution: { "1080P": [6] },
			imageAspectRatio: "adaptive",
			maximumReferences: 1,
			supportsGenerateAudio: false,
			accountAccessNotice: "必须输入一张首帧；1080P 仅支持 6 秒，画幅由首帧决定。",
		},
	},
	"Vidu Q3 Pro": {
		apiModelId: "viduq3-pro",
		operation: "task",
		inputModes: ["text", "image"],
		defaults: { resolution: "720p", duration: 5, ratio: "16:9", generate_audio: true },
		constraints: {
			acceptedResolutions: ["540p", "720p", "1080p"],
			acceptedAspectRatios: ["16:9", "9:16", "3:4", "4:3", "1:1"],
			minimumDuration: 1,
			maximumDuration: 16,
			supportsGenerateAudio: true,
			maximumReferences: 2,
		},
	},
	"PixVerse V6": {
		apiModelId: "v6",
		operation: "task",
		inputModes: ["text"],
		defaults: { resolution: "720p", duration: 5, ratio: "16:9" },
		constraints: {
			acceptedResolutions: ["360p", "540p", "720p", "1080p"],
			acceptedAspectRatios: ["16:9", "4:3", "1:1", "3:4", "9:16", "2:3", "3:2", "21:9"],
			minimumDuration: 1,
			maximumDuration: 15,
			supportsGenerateAudio: true,
			maximumReferences: 0,
		},
	},
	"Veo 3.1": {
		apiModelId: "veo-3.1-generate-preview",
		operation: "task",
		inputModes: ["text"],
		defaults: { resolution: "720p", duration: 8, ratio: "16:9" },
		constraints: {
			acceptedResolutions: ["720p", "1080p", "4k"],
			acceptedAspectRatios: ["16:9", "9:16"],
			minimumDuration: 4,
			maximumDuration: 8,
			acceptedDurations: [4, 6, 8],
			durationByResolution: { "1080p": [8], "4k": [8] },
			supportsGenerateAudio: false,
			maximumReferences: 0,
			accountAccessNotice: "官方生成默认带音频，当前接口没有关闭音频的选项。",
		},
	},
	"Veo 3.1 Lite": {
		apiModelId: "veo-3.1-lite-generate-preview",
		operation: "task",
		inputModes: ["text"],
		defaults: { resolution: "720p", duration: 8, ratio: "16:9" },
		constraints: {
			acceptedResolutions: ["720p", "1080p"],
			acceptedAspectRatios: ["16:9", "9:16"],
			minimumDuration: 4,
			maximumDuration: 8,
			acceptedDurations: [4, 6, 8],
			durationByResolution: { "1080p": [8] },
			supportsGenerateAudio: false,
			maximumReferences: 0,
			accountAccessNotice: "官方生成默认带音频，当前接口没有关闭音频的选项。",
		},
	},
	"GPT-Image-2.5 Flare": {
		apiModelId: "gpt-image-2.5-flare",
		operation: "generation",
		inputModes: ["text", "image"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: {
			acceptedSizes: ["1K", "2K"],
			acceptedAspectRatios: ["1:1", "2:3", "3:2", "3:4", "4:3", "9:16", "16:9"],
			maximumReferences: 16,
			maximumOutputs: 4,
		},
	},
	"GPT-Image-2.5 Sunburst": {
		apiModelId: "gpt-image-2.5-sunburst",
		operation: "generation",
		inputModes: ["text", "image"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: {
			acceptedSizes: ["1K", "2K"],
			acceptedAspectRatios: ["1:1", "2:3", "3:2", "3:4", "4:3", "9:16", "16:9"],
			maximumReferences: 16,
			maximumOutputs: 4,
		},
	},
	"Grok Imagine": {
		apiModelId: "grok-imagine-image",
		operation: "generation",
		inputModes: ["text"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: {
			acceptedSizes: ["1K", "2K"],
			acceptedAspectRatios: ["1:1", "3:2", "2:3", "16:9", "9:16"],
			maximumReferences: 0,
			maximumOutputs: 4,
		},
	},
	"Agnes Image 2.0 Flash": {
		apiModelId: "agnes-image-2.0-flash",
		operation: "generation",
		inputModes: ["text"],
		defaults: { size: "2K", ratio: "1:1" },
		constraints: {
			acceptedSizes: ["1K", "2K", "4K"],
			acceptedAspectRatios: ["1:1", "2:3", "3:2", "9:16", "16:9"],
			maximumReferences: 0,
			maximumOutputs: 1,
		},
	},
	"Agnes Image 2.1 Flash": {
		apiModelId: "agnes-image-2.1-flash",
		operation: "generation",
		inputModes: ["text"],
		defaults: { size: "2K", ratio: "1:1" },
		constraints: {
			acceptedSizes: ["1K", "2K", "4K"],
			acceptedAspectRatios: ["1:1", "2:3", "3:2", "9:16", "16:9"],
			maximumReferences: 0,
			maximumOutputs: 1,
		},
	},
	"MiniMax Music 2.6": {
		apiModelId: "music-2.6",
		operation: "music",
		apiBaseUrl: "https://api.minimax.io/v1",
		inputModes: ["text"],
		defaults: { format: "mp3", sample_rate: 44100, bitrate: 256000, lyrics_optimizer: true },
		unavailableReason: "官方仅向已有 Music 2.6 付费/M方案账户开放；2026-08-20 后的新账户不能开通此版本。",
		constraints: { maximumPromptCharacters: 2000, maximumLyricsCharacters: 3500, maximumReferences: 0 },
	},
	"Doubao TTS v1": {
		apiModelId: "seed-tts-1.1",
		providerId: "doubao-voice-v1",
		brandId: "volcengine",
		operation: "speech",
		inputModes: ["text"],
		requiredCredentials: ["appId", "accessToken", "voiceId"],
		defaults: { format: "mp3", sample_rate: 16000 },
		unavailableReason: "旧版兼容接口；需独立 AppID、Access Token 和 v1 音色，官方推荐使用 v2。",
	},
	"Banana 2": {
		apiModelId: "gemini-3.1-flash-image",
		inputModes: ["text", "image"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: { acceptedSizes: ["0.5K", "1K", "2K", "4K"], maximumReferences: 14, maximumOutputs: 1 },
	},
	"Banana 2 Lite": {
		apiModelId: "gemini-3.1-flash-lite-image",
		inputModes: ["text", "image"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: { acceptedSizes: ["1K"], maximumReferences: 14, maximumOutputs: 1 },
	},
	"Banana Pro": {
		apiModelId: "gemini-3-pro-image",
		inputModes: ["text", "image"],
		defaults: { size: "1K", ratio: "1:1" },
		constraints: { acceptedSizes: ["1K", "2K", "4K"], maximumReferences: 14, maximumOutputs: 1 },
	},
	"Seedream 5.0": {
		apiModelId: "doubao-seedream-5-0-260128",
		inputModes: ["text", "image"],
		defaults: { size: "2K", ratio: "1:1", sequential_image_generation: "auto" },
		constraints: { acceptedSizes: ["2K", "3K", "4K"], maximumReferences: 14, maximumOutputs: 4 },
	},
	"Seedream 5.0 Pro": {
		apiModelId: "doubao-seedream-5-0-pro-260628",
		inputModes: ["text", "image"],
		defaults: { size: "2K", ratio: "1:1" },
		constraints: { acceptedSizes: ["1K", "1.5K", "2K"], maximumReferences: 10, maximumOutputs: 1 },
	},
	"Qwen Image Edit Plus": {
		apiModelId: "qwen-image-edit-plus",
		operation: "edit",
		inputModes: ["image"],
		defaults: { size: "1024*1024", ratio: "1:1" },
		constraints: { acceptedSizes: ["1024*1024"], maximumReferences: 3, maximumOutputs: 4 },
	},
	"Wan 2.7 Image Pro": {
		apiModelId: "wan2.7-image-pro",
		operation: "generation",
		inputModes: ["text", "image"],
		defaults: { size: "2K", ratio: "1:1" },
		constraints: { acceptedSizes: ["2K", "4K"], maximumReferences: 9, maximumOutputs: 4 },
	},
	"Z-Image Turbo": {
		apiModelId: "z-image-turbo",
		inputModes: ["text"],
		defaults: { size: "1024*1024", ratio: "1:1" },
		constraints: { acceptedSizes: ["1024*1024"], maximumReferences: 0, maximumOutputs: 1 },
	},
	"Grok Imagine Video": {
		apiModelId: "grok-imagine-video",
		inputModes: ["text"],
		defaults: { ratio: "16:9", resolution: "480p", generate_audio: true },
		constraints: {
			minimumDuration: 1,
			maximumDuration: 15,
			acceptedResolutions: ["480p", "720p"],
			supportsGenerateAudio: true,
		},
	},
	"Grok Imagine Video 1.5": {
		apiModelId: "grok-imagine-video-1.5",
		inputModes: ["text"],
		defaults: { ratio: "16:9", resolution: "480p", generate_audio: true },
		constraints: {
			minimumDuration: 1,
			maximumDuration: 15,
			acceptedResolutions: ["480p", "720p", "1080p"],
			supportsGenerateAudio: true,
		},
	},
	"Wan 3.0": {
		apiModelId: "wan3.0-video",
		providerId: "alibaba-video",
		brandId: "alibaba",
		inputModes: ["text"],
		defaults: { ratio: "adaptive", resolution: "1080P", duration: 5 },
		constraints: {
			minimumDuration: 2,
			maximumDuration: 30,
			acceptedResolutions: ["1080P"],
			supportsGenerateAudio: true,
		},
	},
	"MiniMax H3": {
		apiModelId: "MiniMax-H3",
		apiBaseUrl: "https://api.minimax.io",
		inputModes: ["text"],
		defaults: { ratio: "16:9", resolution: "768P", duration: 6 },
		constraints: {
			minimumDuration: 4,
			maximumDuration: 15,
			acceptedResolutions: ["768P", "2K"],
			acceptedAspectRatios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"],
		},
	},
	"MiniMax Speech 2.8 HD": {
		apiModelId: "speech-2.8-hd",
		operation: "speech",
		apiBaseUrl: "https://api.minimax.io/v1",
		inputModes: ["text"],
		requiredCredentials: ["voiceId"],
		defaults: { format: "mp3" },
	},
	"MiniMax Speech 2.8 Turbo": {
		apiModelId: "speech-2.8-turbo",
		operation: "speech",
		apiBaseUrl: "https://api.minimax.io/v1",
		inputModes: ["text"],
		requiredCredentials: ["voiceId"],
		defaults: { format: "mp3" },
	},
	"ElevenLabs Voice Changer": {
		apiModelId: "eleven_multilingual_sts_v2",
		operation: "voice-change",
		inputModes: ["audio"],
		requiredCredentials: ["voiceId"],
		defaults: { output_format: "mp3_44100_128" },
		constraints: { maximumReferences: 1 },
	},
	"Fish Audio S1": { apiModelId: "s1", operation: "speech", inputModes: ["text"], defaults: { format: "mp3" } },
	"Fish Audio S2 Pro": {
		apiModelId: "s2-pro",
		operation: "speech",
		inputModes: ["text"],
		defaults: { format: "mp3" },
	},
	"Doubao TTS v2": {
		apiModelId: "seed-tts-2.0",
		providerId: "doubao-voice",
		brandId: "volcengine",
		operation: "speech",
		inputModes: ["text"],
		requiredCredentials: ["voiceId"],
		defaults: { format: "mp3" },
	},
	"Kling V3": {
		apiModelId: "kling-v3",
		operation: "task",
		inputModes: ["text"],
		defaults: { duration: 5, resolution: "720P", ratio: "16:9", generate_audio: false },
		constraints: {
			minimumDuration: 3,
			maximumDuration: 15,
			acceptedResolutions: ["720P", "1080P", "4K"],
			acceptedAspectRatios: ["16:9", "9:16", "1:1"],
			supportsGenerateAudio: true,
			maximumPromptLength: 2500,
		},
	},
	"Kling 3.0 Omni": {
		apiModelId: "kling-v3-omni",
		operation: "task",
		inputModes: ["text"],
		defaults: { duration: 5, resolution: "720P", ratio: "16:9", generate_audio: false },
		constraints: {
			minimumDuration: 3,
			maximumDuration: 15,
			acceptedResolutions: ["720P", "1080P", "4K"],
			acceptedAspectRatios: ["16:9", "9:16", "1:1"],
			supportsGenerateAudio: true,
			maximumPromptLength: 2500,
		},
	},
};

for (const [name, id, providerId, resolutions] of [
	["Seedance 2.0", "doubao-seedance-2-0-260128", "volcengine-ark", ["480p", "720p", "1080p", "4k"]],
	["Seedance 2.0 Fast", "doubao-seedance-2-0-fast-260128", "volcengine-ark", ["480p", "720p"]],
	["Seedance 2.0 Mini", "doubao-seedance-2-0-mini-260615", "volcengine-ark", ["480p", "720p"]],
	["BytePlus Seedance 2.0", "dreamina-seedance-2-0-260128", "byteplus", ["480p", "720p", "1080p", "4k"]],
	["BytePlus Seedance 2.0 Fast", "dreamina-seedance-2-0-fast-260128", "byteplus", ["480p", "720p"]],
	["BytePlus Seedance 2.0 Mini", "dreamina-seedance-2-0-mini-260615", "byteplus", ["480p", "720p"]],
] as const) {
	OFFICIAL_MEDIA_MODELS[name] = {
		apiModelId: id,
		providerId,
		brandId: providerId === "byteplus" ? "byteplus" : "volcengine",
		operation: "task",
		inputModes: ["text", "image", "video", "audio"],
		defaults: { resolution: "720p", duration: 5, ratio: "adaptive", generate_audio: true },
		constraints: {
			acceptedResolutions: [...resolutions],
			acceptedAspectRatios: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16", "adaptive"],
			minimumDuration: 4,
			maximumDuration: 15,
			supportsGenerateAudio: true,
			maximumReferences: 50,
		},
	};
}

const imageRatios = ["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9"];
for (const name of [
	"Banana 2",
	"Banana 2 Lite",
	"Banana Pro",
	"Seedream 5.0",
	"Seedream 5.0 Pro",
	"Qwen Image Edit Plus",
	"Wan 2.7 Image Pro",
	"Z-Image Turbo",
]) {
	const constraints = OFFICIAL_MEDIA_MODELS[name].constraints as Record<string, unknown>;
	constraints.acceptedAspectRatios =
		name === "Banana 2" ? [...imageRatios, "1:4", "1:8", "4:1", "8:1"] : [...imageRatios];
}
for (const name of ["Grok Imagine Video", "Grok Imagine Video 1.5"]) {
	(OFFICIAL_MEDIA_MODELS[name].constraints as Record<string, unknown>).acceptedAspectRatios = [
		"1:1",
		"16:9",
		"9:16",
		"4:3",
		"3:4",
		"3:2",
		"2:3",
	];
}
(OFFICIAL_MEDIA_MODELS["Wan 3.0"].constraints as Record<string, unknown>).acceptedAspectRatios = [
	"adaptive",
	"21:9",
	"16:9",
	"4:3",
	"1:1",
	"3:4",
	"9:16",
];
(OFFICIAL_MEDIA_MODELS["Wan 3.0"].constraints as Record<string, unknown>).acceptedResolutions = [
	"480P",
	"720P",
	"1080P",
];
(OFFICIAL_MEDIA_MODELS["MiniMax Music 2.6"].constraints as Record<string, unknown>).accountAccessNotice =
	OFFICIAL_MEDIA_MODELS["MiniMax Music 2.6"].unavailableReason;
OFFICIAL_MEDIA_MODELS["Doubao TTS v1"].constraints = {
	accountAccessNotice: OFFICIAL_MEDIA_MODELS["Doubao TTS v1"].unavailableReason,
	maximumTextBytes: 1024,
};
(OFFICIAL_MEDIA_MODELS["Vidu Q3 Pro"].constraints as Record<string, unknown>).imageAspectRatio = "adaptive";
(OFFICIAL_MEDIA_MODELS["Vidu Q3 Pro"].constraints as Record<string, unknown>).firstLastFrameAspectRatio = "adaptive";
for (const name of [
	"Seedance 2.0",
	"Seedance 2.0 Fast",
	"Seedance 2.0 Mini",
	"BytePlus Seedance 2.0",
	"BytePlus Seedance 2.0 Fast",
	"BytePlus Seedance 2.0 Mini",
]) {
	(OFFICIAL_MEDIA_MODELS[name].constraints as Record<string, unknown>).firstLastFrameAspectRatio = "adaptive";
}
